name: 'Vigiti Code Analysis'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write
  contents: read

jobs:
  vigiti-code-analysis:
    name: Vigiti Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Prepare output dir'
        run: mkdir -p out

      - name: 'Run Vigiti Code Analysis'
        # Se você versionou a imagem corrigida, troque o tag abaixo (ex.: v1.0.1)
        uses: docker://smmyth/vigiti-runner:v1.0.0-mvp
        env:
          VIGITI_TOKEN: ${{ secrets.VIGITI_TOKEN }}
          VIGITI_API_URL: 'https://runner-278759733579.southamerica-east1.run.app'
          OUTPUT_DIR: '/github/workspace/out'
        with:
          args: >
            scan
            --path /github/workspace
            --output /github/workspace/out
            --summary
            --ropa
            --sarif /github/workspace/out/results.sarif
            --debug

      - name: 'Upload SARIF to GitHub Security'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'out/results.sarif'
          checkout_path: ${{ github.workspace }}
          wait-for-processing: true

      # Opcional: manter artefatos para auditoria/depuração.
      - name: 'Upload analysis artifacts'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vigiti-out
          path: out/**
